name: MLflow CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install Dependencies
        run: |
          pip install mlflow
          pip install scikit-learn
          pip install pandas
          pip install matplotlib

      - name: Run MLflow Project
        run: |
          python -m mlflow run MLProject
